name: Build CSS

on:
  push:
    branches: [ main ]
    paths: 
      - 'css/build.css'
      - 'css/base/**/*.css'
      - 'css/components/**/*.css'
      - 'css/layout/**/*.css'
      - 'css/utilities/**/*.css'
  workflow_dispatch:

# Prevent concurrent CSS builds
concurrency:
  group: "css-build"
  cancel-in-progress: true

jobs:
  build-css:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install CSS build tools
      run: |
        npm install --no-package-lock postcss-import autoprefixer postcss-cli
        
    - name: Build CSS
      run: |
        echo "Building CSS from build.css to main.css..."
        
        # Build CSS with imports processed from build.css to main.css
        npx postcss css/build.css -o css/main.css --use postcss-import autoprefixer
        
        echo "CSS built successfully!"
        echo "Source file: css/build.css"
        echo "Output file: css/main.css"
        echo "Output size: $(wc -c < css/main.css) bytes"
        
    - name: Commit built CSS
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add css/main.css
        if git diff --staged --quiet; then
          echo "No changes to compiled CSS"
        else
          git commit -m "🎨 Auto-build CSS from build.css [skip ci]"
          git push
        fi