name: Build CSS for GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install postcss-cli and postcss-import
      run: |
        npm install -g postcss-cli
        npm install postcss-import autoprefixer
        
    - name: Build CSS
      run: |
        npx postcss css/main.css -o css/main.css --use postcss-import
        
    - name: Commit built CSS
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add css/main.css
        git diff --staged --quiet || git commit -m "Build CSS for deployment"
        git push